name: Fetch Google Analytics Data

on:
  push:
    branches:
      - master
  workflow_dispatch:  

jobs:
  get-analytics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Use Google Analytics key
        run: |
          echo "${{ secrets.GOOGLE_ANALYTICS_KEY }}" > google-analytics-key.json

      - name: Run Python script to fetch analytics data
        run: python pyscripts/get_analytics_data.py

      - name: Commit and push JSON data
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add public/analytics_data.json
          git commit -m "Update Google Analytics data"
          git push
