name: Fetch Google Analytics Data

on:
  push:
    branches:
      - master
  workflow_dispatch:  

jobs:
  get-analytics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google.analytics.data_v1beta itertools pandas os

      - name: Use Google Analytics key
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: python pyscripts/get_analytics_data.py

      - name: Commit and push csv data
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add files/file.csv
          git commit -m "Update Google Analytics data"
          git push
