name: Fetch Google Analytics Data

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜 (UTC 时间) 运行

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Google Client Library
      run: pip install --upgrade google-api-python-client google-auth-httplib2

    - name: Fetch Google Analytics Data
      env:
        GA_SERVICE_ACCOUNT_KEY: ${{ secrets.GA_SERVICE_ACCOUNT_KEY }}
        GA_VIEW_ID: ${{ secrets.GA_VIEW_ID }}
      run: |
        # 使用 base64 编码的私钥解码为字符串
        echo "$GA_SERVICE_ACCOUNT_KEY" > service_account_key.json
        # 你的 Python 脚本或调用 Google Analytics API 的命令
        python scripts/fetch_analytics_data.py